# Generated by Django 5.1.3 on 2024-11-16 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('field', models.TextField(blank=True)),
                ('funds', models.IntegerField()),
                ('available_positions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('social_media', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='base.project')),
            ],
        ),
    ]
