# Generated by Django 5.1.3 on 2024-11-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='posistion',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
